### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by byx2020** [BillYang2016/nightbot#1]
1. > groups: 0 # 输入群号，使用','分割`

可以增加选择所有群的选项，单个输入群号对于群较多的机器人比较麻烦。

2. > time:
    >   start_hour: 6 # 跨日时间（默认早上6点）
    >   morning: # 允许早安区间（0-24时）
    >     accept_start_hour: 0
    >     accept_end_hour: 24
    >   night: # 允许晚安区间（0-24时）
    >     accept_start_hour: 0
    >     accept_end_hour: 24

晚安区间想设置为当日晚上18点到次日凌晨4点应该如何设置，是`accept_start_hour: 18`和`accept_end_hour: 4`吗？

3. 之后是否会增加允许多个群早晚安数据互通的可选项？对于部分活跃人数较少的群，数据互通是有一定的必要性的

4. 回复能否设置为空？目前在`config.yml`中不填会回复null。
![21014.png](https://i.loli.net/2021/01/06/DazLZN2CJYVWiqG.png)

**Comment by BillYang2016** [comment]
1. 后续会加入
2. 在1.0.5版本确实如此，需要注意`accept_end_hour`也就是凌晨4点不允许晚安，比如4点半就是不允许的
3. 这一项对代码的改动较大，懒了（等一个pr）
4. 后续会加入
5. 关于其他用户提到的限制“秒早安”和“秒晚安”也在计划中了

**Comment by BillYang2016** [comment]
Added in [v1.0.6](https://github.com/BillYang2016/nightbot/releases/tag/v1.0.6), closing the issue.
